#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

use App\Command\InstallCommand;
use App\Command\UpdateCommand;
use Symfony\Component\Console\Application;

$app = require __DIR__ . '/../bootstrap.php';

$application = new Application();
$application->add(new InstallCommand($app));
$application->add(new UpdateCommand($app));
$application->run();
